---
title: Cachitos. Segunda parte
author: jlcr
date: '2021-01-13'
slug: cachitos-segunda-parte
categories:
  - estadística
  - polémica
tags:
  - análisis
  - textmining
  - ocr
description: ''
topics: []
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>En el <a href="https://muestrear-no-es-pecado.netlify.app/2021/01/11/cachitos-primera-parte/">post anterior</a> vimos como extraer 1 de cada n fotogramas de un video, recortar una zona en concreto y pasarle un software de reconocimiento óptico de caracteres para tener el texto. En esta parte vamos a ver como leer esos ficheros de texto y también una de las formas de quitar subtítulos duplicados. Para eso vamos a utilizar R.
Vamos al lío.</p>
<p>Ejecuto el script <code>extract_subtitles.sh</code> del post anterior de la siguiente forma.</p>
<pre class="bash"><code>./extract_subtitles.sh 2020
./extract_subtitles.sh 2019</code></pre>
<p>Se baja el video desde alacarta, recorta los subtítulos y obtiene el texto. La estructura de directorios que me crea en dónde le haya dicho que es el <code>root_directory</code> es</p>
<pre class="bash"><code>
╰─ $ ▶ tree -d
.
├── 2019_txt
├── 2020_txt
└── video
    ├── 2019_jpg
    └── 2020_jpg
</code></pre>
<p>Dónde en video tenemos los dos videos en mp4, y los directorios con los fotogramas originales junto con los subtítulos, y en los directorios anno_txt cada uno de los ficheros de texto correspondientes a los fotogramas.</p>
<pre class="bash"><code>╰─ $ ▶ ll 2020_txt | head -n 20
total 5456
drwxrwxr-x 2 jose jose 77824 ene 11 20:51 ./
drwxrwxr-x 8 jose jose  4096 ene 13 19:41 ../
-rw-rw-r-- 1 jose jose     1 ene  4 13:07 00000001.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     1 ene  4 13:06 00000002.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     1 ene  4 13:07 00000003.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     1 ene  4 13:08 00000004.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     3 ene  4 13:07 00000005.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     3 ene  4 13:07 00000006.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     3 ene  4 13:07 00000007.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     3 ene  4 13:06 00000008.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     1 ene  4 13:07 00000009.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     3 ene  4 13:08 00000010.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     1 ene  4 13:08 00000011.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     6 ene  4 13:07 00000012.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose    24 ene  4 13:06 00000013.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose    94 ene  4 13:07 00000014.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose    65 ene  4 13:07 00000015.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose    93 ene  4 13:06 00000016.jpg.subtitulo.tif.txt
-rw-rw-r-- 1 jose jose     1 ene  4 13:06 00000017.jpg.subtitulo.tif.txt


╰─ $ ▶ ll 2020_txt | wc -l
1347

</code></pre>
<p>Y vemos que hay 1347 ficheros txt, y algunos muy pequeños (los que no tienen texto)</p>
<p>Veamos el <code>00000016.jpg.subtitulo.tif.txt</code></p>
<pre class="bash"><code>╰─ $ ▶ cat 2020_txt/00000016.jpg.subtitulo.tif.txt
Viendo la actitud del público, más que una actuación
esto es una sesión de coaching.</code></pre>
<p>Pues vamos a leerlos todos usando R.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.0.4     ✓ dplyr   1.0.2
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>root_directory = &quot;~/canadasreche@gmail.com/public/proyecto_cachitos/&quot;
anno &lt;- &quot;2020&quot;

# Construims un data frame con los nombrs de los ficheros 

nombre_ficheros &lt;- list.files(path = str_glue(&quot;{root_directory}{anno}_txt/&quot;)) %&gt;% 
    enframe() %&gt;% 
    rename(n_fichero = value)

nombre_ficheros</code></pre>
<pre><code>## # A tibble: 1,344 x 2
##     name n_fichero                     
##    &lt;int&gt; &lt;chr&gt;                         
##  1     1 00000001.jpg.subtitulo.tif.txt
##  2     2 00000002.jpg.subtitulo.tif.txt
##  3     3 00000003.jpg.subtitulo.tif.txt
##  4     4 00000004.jpg.subtitulo.tif.txt
##  5     5 00000005.jpg.subtitulo.tif.txt
##  6     6 00000006.jpg.subtitulo.tif.txt
##  7     7 00000007.jpg.subtitulo.tif.txt
##  8     8 00000008.jpg.subtitulo.tif.txt
##  9     9 00000009.jpg.subtitulo.tif.txt
## 10    10 00000010.jpg.subtitulo.tif.txt
## # … with 1,334 more rows</code></pre>
<p>Ahora los podemos leer en orden</p>
<pre class="r"><code>subtitulos &lt;-  list.files(path = str_glue(&quot;{root_directory}{anno}_txt/&quot;), 
                        pattern = &quot;*.txt&quot;, full.names = TRUE) %&gt;% 
    map(~read_file(.)) %&gt;% 
    enframe() %&gt;%  
  # hacemos el join con el dataframe anterior para tener el nombre del fichero original
    left_join(nombre_ficheros)</code></pre>
<pre><code>## Joining, by = &quot;name&quot;</code></pre>
<pre class="r"><code>glimpse(subtitulos)</code></pre>
<pre><code>## Rows: 1,344
## Columns: 3
## $ name      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
## $ value     &lt;list&gt; [&quot;\f&quot;, &quot;\f&quot;, &quot;\f&quot;, &quot;\f&quot;, &quot; \n\f&quot;, &quot; \n\f&quot;, &quot; \n\f&quot;, &quot; \n\f…
## $ n_fichero &lt;chr&gt; &quot;00000001.jpg.subtitulo.tif.txt&quot;, &quot;00000002.jpg.subtitulo.t…</code></pre>
<pre class="r"><code>subtitulos</code></pre>
<pre><code>## # A tibble: 1,344 x 3
##     name value     n_fichero                     
##    &lt;int&gt; &lt;list&gt;    &lt;chr&gt;                         
##  1     1 &lt;chr [1]&gt; 00000001.jpg.subtitulo.tif.txt
##  2     2 &lt;chr [1]&gt; 00000002.jpg.subtitulo.tif.txt
##  3     3 &lt;chr [1]&gt; 00000003.jpg.subtitulo.tif.txt
##  4     4 &lt;chr [1]&gt; 00000004.jpg.subtitulo.tif.txt
##  5     5 &lt;chr [1]&gt; 00000005.jpg.subtitulo.tif.txt
##  6     6 &lt;chr [1]&gt; 00000006.jpg.subtitulo.tif.txt
##  7     7 &lt;chr [1]&gt; 00000007.jpg.subtitulo.tif.txt
##  8     8 &lt;chr [1]&gt; 00000008.jpg.subtitulo.tif.txt
##  9     9 &lt;chr [1]&gt; 00000009.jpg.subtitulo.tif.txt
## 10    10 &lt;chr [1]&gt; 00000010.jpg.subtitulo.tif.txt
## # … with 1,334 more rows</code></pre>
<p>en n_fichero tenemos el nombre y en value el texto</p>
<pre class="r"><code>subtitulos %&gt;% 
  pull(value) %&gt;%
  ## usamos `[[` que es el operador para acceder a la lista el que normalemente se usa [[nombre_elemento]]
  `[[`(16)</code></pre>
<pre><code>## [1] &quot;Viendo la actitud del público, más que una actuación\nesto es una sesión de coaching.\n\n \n\f&quot;</code></pre>
<pre class="r"><code># equivalentemente

# subtitulos %&gt;% 
#     pull(value) %&gt;% 
#     pluck(16)</code></pre>
<p>Como sabemos que hay muchos ficheros sin texto podemos contar letras.</p>
<pre class="r"><code>subtitulos &lt;- subtitulos %&gt;% 
    mutate(n_caracteres = nchar(value)) 

subtitulos %&gt;% 
    group_by(n_caracteres) %&gt;% 
    count()</code></pre>
<pre><code>## # A tibble: 127 x 2
## # Groups:   n_caracteres [127]
##    n_caracteres     n
##           &lt;int&gt; &lt;int&gt;
##  1            1   480
##  2            3   125
##  3            4    17
##  4            5     7
##  5            6    13
##  6            7     2
##  7            8     7
##  8            9     6
##  9           10     4
## 10           11     5
## # … with 117 more rows</code></pre>
<p>Y vemos que hay muchos subtitulos con pocos caracteres. Si vemos por ejemplo los que tienen 8 caracteres</p>
<pre class="r"><code>subtitulos %&gt;% 
    filter(n_caracteres ==8) %&gt;% 
    pull(value)</code></pre>
<pre><code>## [[1]]
## [1] &quot;LEN As\n\f&quot;
## 
## [[2]]
## [1] &quot;pro\n\nÑ\n\f&quot;
## 
## [[3]]
## [1] &quot;ñ Xd a\n\f&quot;
## 
## [[4]]
## [1] &quot;/ EI\nE\n\f&quot;
## 
## [[5]]
## [1] &quot;TOY ES\n\f&quot;
## 
## [[6]]
## [1] &quot;110\n\ny\n\f&quot;
## 
## [[7]]
## [1] &quot;steria\n\f&quot;</code></pre>
<p>Que se corresponden con haber pillado parte no del subtítulo sino del nombre de la actuación</p>
<pre class="r"><code>subtitulos %&gt;% 
    filter(n_caracteres ==8)</code></pre>
<pre><code>## # A tibble: 7 x 4
##    name value     n_fichero                      n_caracteres
##   &lt;int&gt; &lt;list&gt;    &lt;chr&gt;                                 &lt;int&gt;
## 1   207 &lt;chr [1]&gt; 00000207.jpg.subtitulo.tif.txt            8
## 2   252 &lt;chr [1]&gt; 00000252.jpg.subtitulo.tif.txt            8
## 3   321 &lt;chr [1]&gt; 00000321.jpg.subtitulo.tif.txt            8
## 4   339 &lt;chr [1]&gt; 00000339.jpg.subtitulo.tif.txt            8
## 5   442 &lt;chr [1]&gt; 00000442.jpg.subtitulo.tif.txt            8
## 6   494 &lt;chr [1]&gt; 00000494.jpg.subtitulo.tif.txt            8
## 7   722 &lt;chr [1]&gt; 00000722.jpg.subtitulo.tif.txt            8</code></pre>
<p>Usando la librería <code>magick</code> en R que permite usar <code>imagemagick</code> en R, ver <strong><a href="https://analisisydecision.es/tratamiento-y-procesado-de-imagenes-con-r-y-magick/">post</a></strong> de Raúl Vaquerizo y su homenaje a Sean Connery, podemos ver el fotgrama correspondiente</p>
<pre class="r"><code>library(magick)</code></pre>
<pre><code>## Linking to ImageMagick 6.9.10.23
## Enabled features: fontconfig, freetype, fftw, lcms, pango, webp, x11
## Disabled features: cairo, ghostscript, rsvg</code></pre>
<pre><code>## Using 12 threads</code></pre>
<pre class="r"><code>(directorio_imagenes &lt;- str_glue(&quot;{root_directory}video/{anno}_jpg/&quot;))</code></pre>
<pre><code>## ~/canadasreche@gmail.com/public/proyecto_cachitos/video/2020_jpg/</code></pre>
<pre class="r"><code>image_read(str_glue(&quot;{directorio_imagenes}00000207.jpg&quot;))</code></pre>
<p><img src="/post/2021-01-13-cachitos-segunda-parte_files/figure-html/unnamed-chunk-7-1.png" width="321" /></p>
<p>También podemos ver hasta cuando pasa eso, por ejemplo si vemos subtítulos con 18 caracteres</p>
<pre class="r"><code>subtitulos %&gt;% 
    filter(n_caracteres ==18) %&gt;% 
    pull(value)</code></pre>
<pre><code>## [[1]]
## [1] &quot; \n\nA BAEZA\n\n ———\n\f&quot;
## 
## [[2]]
## [1] &quot;Descanse en Pau.\n\f&quot;
## 
## [[3]]
## [1] &quot;VEL y BIMBA BOSÉ\n\f&quot;
## 
## [[4]]
## [1] &quot;IIS &gt;&gt;\n\npd.\ndd &gt;\n\f&quot;</code></pre>
<p>Vemos que también pasa, pero ya vamos pillando rótulos de verdad como el “Descanse en Pau” que pusieron ante una actuación de Pau Donés.</p>
<p>Como vemos hay que hacer limpieza, pero por el momento vamos a quedarnos con los subtítulos con número de caracteres mayor de 17. Esta decisión hace que perdamos algunos subtítulos de verdad, como por ejemplo el conocido “Loco Vox”.</p>
<pre class="r"><code>subtitulos &lt;- subtitulos %&gt;% 
    filter(n_caracteres &gt; 17) 

glimpse(subtitulos)</code></pre>
<pre><code>## Rows: 664
## Columns: 4
## $ name         &lt;int&gt; 13, 14, 15, 16, 19, 20, 21, 22, 25, 26, 27, 31, 32, 33, …
## $ value        &lt;list&gt; [&quot; \n\nA BAEZA\n\n ———\n\f&quot;, &quot;Después del añito que hem…
## $ n_fichero    &lt;chr&gt; &quot;00000013.jpg.subtitulo.tif.txt&quot;, &quot;00000014.jpg.subtitul…
## $ n_caracteres &lt;int&gt; 18, 92, 62, 89, 50, 112, 114, 114, 31, 91, 78, 117, 98, …</code></pre>
<p>Pues ya hemos pasado de más de 1000 rótulos a 664. Pero sabemos, por el post anterior que hay algunos duplicados.</p>
<p>Con el fin de detectar cuáles están duplicados y aprovechando que están en orden de aparición, podemos hacer utilizar distancias de texto para calcular la distancia de cada subtítulo con el anterior, y si la distancia es pequeña es que es el mismo rótulo.</p>
<p>Primero hacemos una minilimpieza.</p>
<pre class="r"><code>string_mini_clean &lt;-  function(string){
    string &lt;- gsub(&quot;?\n|\n&quot;, &quot; &quot;, string)
    string &lt;- gsub(&quot;\r|?\f|=&quot;, &quot; &quot;, string)
    string &lt;- gsub(&#39;“|”|—|&gt;&#39;,&quot; &quot;, string)
    
    string &lt;- gsub(&quot;[[:punct:][:blank:]]+&quot;, &quot; &quot;, string)
    string &lt;- tolower(string)
    string &lt;- gsub(&quot;  &quot;, &quot; &quot;, string)
    string &lt;-  
    
    return(string)
}

# Haciendo uso de programacion funciona con purrr es muy fácil pasar esta función a cada elemento. y decirle que # el reultado es string con map_chr

subtitulos_proces &lt;- subtitulos %&gt;% 
    mutate(texto = map_chr(value, string_mini_clean)) %&gt;% 
    select(-value)

subtitulos_proces %&gt;% 
  select(texto)</code></pre>
<pre><code>## # A tibble: 664 x 1
##    texto                                                                        
##    &lt;chr&gt;                                                                        
##  1 &quot; a baeza &quot;                                                                  
##  2 &quot;después del añito que hemos pasado quien mm aman 110 se consuela es porque …
##  3 &quot;viendo la actitud del público más que una actuación esto es &quot;               
##  4 &quot;viendo la actitud del público más que una actuación esto es una sesión de c…
##  5 &quot; intura y su conjunto conga del jaruco 2 &quot;                                  
##  6 &quot;la última vez que hiciste algo parecido fue en el súper y llevabas 25 rollo…
##  7 &quot; a que produce nostalgia ver a un grupo de españoles p poniéndose de acuerd…
##  8 &quot; a que produce nostalgia ver a un grupo de españoles poniéndose de acuerdo …
##  9 &quot;jno lomas xte conmigo pi &quot;                                                  
## 10 &quot;í 7 igual lo que nos ha caído es una maldición india rel y este es el orige…
## # … with 654 more rows</code></pre>
<p>Y ya vemos a simple vista que hay algun duplicado. Calculemos ahora la distancia de strings, utilizando la función <code>stringdist</code> de la librería del mismo nombre.</p>
<pre class="r"><code>subtitulos_proces %&gt;% 
    mutate(texto_anterior = lag(texto)) %&gt;% 
    # calculamos distancias con método lcs (que no me he leído que hace exactamente)
    mutate(distancia = stringdist::stringdist(texto, texto_anterior, method = &quot;lcs&quot;)) %&gt;% 
  # veamos algunos elementos
    filter(distancia &lt; 10) %&gt;% 
    arrange(desc(distancia) ) %&gt;% 
    select(texto, texto_anterior, distancia) %&gt;% 
    head()</code></pre>
<pre><code>## # A tibble: 6 x 3
##   texto                           texto_anterior                       distancia
##   &lt;chr&gt;                           &lt;chr&gt;                                    &lt;dbl&gt;
## 1 &quot;mn por si no te lo ha dicho a… &quot;a si no te lo ha dicho aún tu cuña…         9
## 2 &quot;por alguna razón a beyoncé le… &quot; zz por alguna razón a beyoncé le …         6
## 3 &quot;asi es como se visten los daf… &quot;asi es como se visten los daft pun…         6
## 4 &quot;la pandemia interrumpió su gi… &quot;la pandemia interrumpió su gira de…         6
## 5 &quot;2 xl en viajes al pasado los … &quot;2 xl en viajes al pasado los 80 co…         6
## 6 &quot;lp parece que a nek le ha pil… &quot;parece que a nek le ha pillado des…         6</code></pre>
<p>Y parece que funciona.
Así que decido quitar las filas dónde la distancia sea menos que 19 y así eliminar muchos de los duplicados.</p>
<pre class="r"><code>subtitulos_proces &lt;- subtitulos_proces %&gt;% 
    mutate(texto_anterior = lag(texto)) %&gt;% 
    mutate(distancia = stringdist::stringdist(texto, texto_anterior, method = &quot;lcs&quot;)) %&gt;% 
    filter(distancia &gt; 19) %&gt;% 
    select(-texto_anterior)

subtitulos_proces %&gt;% 
  head()</code></pre>
<pre><code>## # A tibble: 6 x 5
##    name n_fichero         n_caracteres texto                           distancia
##   &lt;int&gt; &lt;chr&gt;                    &lt;int&gt; &lt;chr&gt;                               &lt;dbl&gt;
## 1    14 00000014.jpg.sub…           92 &quot;después del añito que hemos p…        84
## 2    15 00000015.jpg.sub…           62 &quot;viendo la actitud del público…        89
## 3    16 00000016.jpg.sub…           89 &quot;viendo la actitud del público…        23
## 4    19 00000019.jpg.sub…           50 &quot; intura y su conjunto conga d…        76
## 5    20 00000020.jpg.sub…          112 &quot;la última vez que hiciste alg…       103
## 6    21 00000021.jpg.sub…          114 &quot; a que produce nostalgia ver …       128</code></pre>
<p>Y ahora escribimos este dataframe en un csv y será la materia prima para ver qué podemos hacer con esto (para eso requeriré ayuda de algún amigo más ducho en tales artes)</p>
<pre class="r"><code>write_csv(subtitulos_proces,
          file = str_glue(&quot;{root_directory}{anno}_txt_unido.csv&quot;))</code></pre>
<p>Y os dejo este csv en este <a href="https://drive.google.com/file/d/1lWbl1M39NfgGsLfEjZeg8XsyfuqsTrFS/view?usp=sharing">enlace</a></p>
